# Chemin vers ce layer — BBPATH accumule les chemins de tous les layers
BBPATH .= ":${LAYERDIR}"

# Indique à BitBake où trouver les recettes dans ce layer
# ** = récursif, *.bb = recettes, *.bbappend = modifications de recettes existantes
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

# Collections : nom unique du layer (évite les conflits entre layers)
BBFILE_COLLECTIONS += "meta-custom"

# Pattern pour identifier les fichiers appartenant à ce layer
BBFILE_PATTERN_meta-custom = "^${LAYERDIR}/"

# Priorité : en cas de conflit de recette, le layer avec la plus haute priorité gagne
# meta/meta-poky/meta-yocto-bsp sont à 5 — on met 6 pour pouvoir les surcharger
BBFILE_PRIORITY_meta-custom = "6"

# Version de ce layer (pour la compatibilité inter-layers)
LAYERVERSION_meta-custom = "1"

# Déclare la compatibilité avec la version Yocto (scarthgap = 5.0)
LAYERSERIES_COMPAT_meta-custom = "scarthgap styhead"
