# Distro hardened — hérite de poky et renforce la sécurité
require conf/distro/poky.conf

DISTRO = "poky-hardened"
DISTRO_NAME = "Poky Hardened"
DISTRO_VERSION = "1.0"

# CVE checking sur tous les paquets
INHERIT += "cve-check"

# Pas de debug-tweaks par défaut sur toutes les images
DISTRO_FEATURES:remove = "x11"
IMAGE_FEATURES:remove = "debug-tweaks"

# Forcer le mot de passe root vide interdit
ROOTFS_POSTPROCESS_COMMAND:append = " zap_empty_root_password;"

# SELinux
DISTRO_FEATURES:append = " selinux"
PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-targeted"