# slurm.conf — configuration minimale pour le mini-labo HPC
ClusterName=hpclab
ControlMachine=master
SlurmUser=slurm
AuthType=auth/munge
StateSaveLocation=/var/lib/slurm
SlurmdSpoolDir=/var/lib/slurm/slurmd
SwitchType=switch/none
MpiDefault=pmix
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_CPU_Memory
ReturnToService=2
SlurmctldTimeout=120
SlurmdTimeout=300

# Logging
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log

# Nœuds
NodeName=compute01 NodeAddr=192.168.56.11 CPUs=2 RealMemory=900 State=UNKNOWN
NodeName=compute02 NodeAddr=192.168.56.12 CPUs=2 RealMemory=900 State=UNKNOWN
NodeName=compute03 NodeAddr=192.168.56.13 CPUs=2 RealMemory=900 State=UNKNOWN

# Partition
PartitionName=compute Nodes=compute[01-03] Default=YES MaxTime=4:00:00 State=UP
